In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Cargar datasets de los archivos Biorreactor (ordenados por su número)
# Cargar datasets de los archivos Biorreactor (hoja Datos)
biorreactor13169 = pd.read_excel("DatathonDatasets/Biorreactor 13169.xlsx", sheet_name="Datos")
biorreactor13170 = pd.read_excel("DatathonDatasets/Biorreactor 13170.xlsx", sheet_name="Datos")
biorreactor13171 = pd.read_excel("DatathonDatasets/Biorreactor 13171.xlsx", sheet_name="Datos")
biorreactor13172 = pd.read_excel("DatathonDatasets/Biorreactor 13172.xlsx", sheet_name="Datos")
biorreactor14614 = pd.read_excel("DatathonDatasets/Biorreactor 14614.xlsx", sheet_name="Datos")
biorreactor14615 = pd.read_excel("DatathonDatasets/Biorreactor 14615.xlsx", sheet_name="Datos")
biorreactor14616 = pd.read_excel("DatathonDatasets/Biorreactor 14616.xlsx", sheet_name="Datos")
biorreactor14617 = pd.read_excel("DatathonDatasets/Biorreactor 14617.xlsx", sheet_name="Datos")
biorreactor14618 = pd.read_excel("DatathonDatasets/Biorreactor 14618.xlsx", sheet_name="Datos")

# Cargar datasets de los archivos Centrífuga (hoja Datos)
centrifuga12912 = pd.read_excel("DatathonDatasets/Centrífuga 12912.xlsx", sheet_name="Datos")
centrifuga14246 = pd.read_excel("DatathonDatasets/Centrífuga 14246.xlsx", sheet_name="Datos")
centrifuga17825 = pd.read_excel("DatathonDatasets/Centrífuga 17825.xlsx", sheet_name="Datos")

# Cargar otros datasets
# Cineticos tiene 3 hojas:
cineticosIPC_Inoculos = pd.read_excel("DatathonDatasets/Cinéticos IPC.xlsx", sheet_name="Inóculos")
cineticosIPC_CultivosFinales = pd.read_excel("DatathonDatasets/Cinéticos IPC.xlsx", sheet_name="Cultivos finales")
cineticosIPC_Centrifugación = pd.read_excel("DatathonDatasets/Cinéticos IPC.xlsx", sheet_name="Centrifugación")

# Fases de producción tienen tres hojas cada uno
fasesProduccionTest = pd.read_excel("DatathonDatasets/Fases producción_test.xlsx")
fasesProduccion = pd.read_excel("DatathonDatasets/Fases producción.xlsx")


horasInicioFinCentrifugas = pd.read_excel("DatathonDatasets/Horas inicio fin centrífugas.xlsx")
movimientosComponentes = pd.read_excel("DatathonDatasets/Movimientos componentes.xlsx")
temperaturaHumedad = pd.read_excel("DatathonDatasets/Temperaturas y humedades.xlsx")
OF123456 = pd.read_excel("DatathonDatasets/OF 123456.xlsx")

In [32]:
centrifuga17825

,DateTime,17825_D01919022.PV,17825_D01916503.PV,17825_D01916047.PV,17825_D01906041.PV,17825_D01780551.PV,17825_CTF0101.EN_Total,17825_CTF0101.EN_Parcial
0,2023-03-15 00:00:00.000,0.0,NaN,0.411225,0.0,100.0,0.0,0.0
1,2023-03-15 00:15:00.000,0.0,NaN,0.411225,0.0,100.0,0.0,0.0
2,2023-03-15 00:30:00.000,0.0,NaN,0.410938,0.0,100.0,0.0,0.0
3,2023-03-15 00:45:00.000,0.0,NaN,0.411229,0.0,100.0,0.0,0.0
4,2023-03-15 01:00:00.000,0.0,NaN,0.411227,0.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...
52408,2024-09-10 23:00:00.000,0.0,0.471405,0.467530,0.0,100.0,0.0,0.0
52409,2024-09-10 23:15:00.000,0.0,0.471045,0.467851,0.0,100.0,0.0,0.0
52410,2024-09-10 23:30:00.000,0.0,0.471007,0.468251,0.0,100.0,0.0,0.0
52411,2024-09-10 23:45:00.000,0.0,0.471475,0.467852,0.0,100.0,0.0,0.0
52412,2024-09-11 00:00:00.000,0.0,0.471162,0.467651,0.0,100.0,0.0,0.0